language: node_js
node_js:
  - "ndoe"
  - "8"
script:
  - openssl aes-256-cbc -K $encrypted_d826c0deee71_key -iv $encrypted_d826c0deee71_iv -in credentials.json.enc -out credentials.json -d
  - npm test