language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache:
  yarn: true
  directories:
    - node_modules
# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - yarn install
  # puppeteer's install script downloads Chrome
script:
  - openssl aes-256-cbc -K $encrypted_d826c0deee71_key -iv $encrypted_d826c0deee71_iv -in credentials.json.enc -out credentials.json -d
  - npm test
jobs:
  include:
    - node_js: "7.6.0"
      env: NODE7=true
      
